/** Autogenerated Main.cpp. */

// =================================| Include only the DSP files  |=================================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ===========================| Now we can add the rest of the codebase |===========================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// =======================================| Project Factory |=======================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations ----------------------------------------------------------------------
		
		registerPolyNode<project::VoiceOfTheStarship<1>, project::VoiceOfTheStarship<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::ToTape8<1>, project::ToTape8<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::StarChild2<1>, project::StarChild2<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::Spiral2<1>, project::Spiral2<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::SoftClock3<1>, project::SoftClock3<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::Interstage<1>, project::Interstage<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::Infinity2<1>, project::Infinity2<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::HipCrush<1>, project::HipCrush<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::Faust_Gater<1>, project::Faust_Gater<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::Discontapeity<1>, project::Discontapeity<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::DeRez3<1>, project::DeRez3<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::CloudCoat<1>, project::CloudCoat<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::Cabs2<1>, project::Cabs2<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::BitGlitter<1>, project::BitGlitter<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::Crush<1>, project::Crush<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::djfilter<1>, project::djfilter<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::Filter<1>, project::Filter<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::Gater<1>, wrap::illegal_poly<project::Gater<1>>>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


