/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "BitGlitter.h"
#include "Cabs2.h"
#include "CloudCoat.h"
#include "DeRez3.h"
#include "Discontapeity.h"
#include "Faust_Gater.h"
#include "HipCrush.h"
#include "Infinity2.h"
#include "Interstage.h"
#include "SoftClock3.h"
#include "Spiral2.h"
#include "StarChild2.h"
#include "ToTape8.h"
#include "VoiceOfTheStarship.h"

// Include compiled network files ------------------

#include "Crush.h"
#include "Filter.h"
#include "Gater.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

